### ISSUE TITLE
Failed to load resource in Safari 11.1 using file input field in form

### ISSUE THREAD

**Issue by itgi** [in2code-de/powermail_cond#15]
With the latest Safari Version 11.1 Powermail Condition throws an error "Failed to load resource: The operation couldn’t be completed. Protocol error" when using a file input field. The conitions don't apply and all fields are visible. Removing the file field then the error disappears and the form works fine.

**Comment by itgi** [comment]
The error log shows:
`Core: Exception handler (WEB): Uncaught TYPO3 Exception: No powermail parameters are given - e.g. &tx_powermail_pi1[mail][form]=123 | Exception thrown in file /html/gi.de/public/typo3conf/ext/powermail_cond/Classes/Controller/ConditionController.php in line 47.`

**Comment by itgi** [comment]
Is there a solution to this problem?

**Comment by einpraegsam** [comment]
Sounds similar to https://github.com/einpraegsam/powermail/issues/272

**Comment by pixeldesu** [comment]
This issue is 6 years old now and both the Powermail version as well as Safari are far into new versions. If new problems with Safari occur, please open a new issue for them!
