### ISSUE TITLE
TYPO3 9 LTS: Browser blocks mixed content: proposal how to solve it

### ISSUE THREAD

**Issue by chrisprog20** [in2code-de/powermail_cond#40]
TYPO3: 9.5.8
powermail: 7.3.1
powermail_cond: 7.0.0

Hello, 

I just discovered that powermail_cond does not work in browsers blocking mixed content on a TYPO3 9 LTS installation : for example in Firefox 68. Here my situation:

I use a powermail form together with a simple powermail_cond condition on a **https** site.
Investigating the console tab revealed me that the generated absolute ajax url from powermail_cond uses **http**. 

Investigating further I could find the following solution: 

If you replace in the typolink declaration of the page property 3132 the value for "forceAbsoluteUrl" by 0 
the generated ajax url is relative and hence called via https and the condition works.

Side note: This change is not necessary in TYPO3 8 LTS as there the generated ajax url contains https.
I think the different behaviour of url generation has to do with the site configuration introduced in TYPO3 9.

Cheers
Christian

**Comment by pixeldesu** [comment]
This can't be verified on v12 anymore, the AjaxURL for Conditions is HTTPS in any tested scenario.

Due to the issue being relatively old now, and both that version of Powermail and TYPO3 being out of support, I'll close this. If this occurs again, feel free to open a new issue.
