### ISSUE TITLE
SQL error: SQLSTATE[22007]

### ISSUE THREAD

**Issue by Cretection** [in2code-de/powermail_cond#45]
Whenever I want to create a rule I get the following error:
	
`2: SQL error: 'SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column `my_database`.`tx_powermailcond_domain_model_rule`.`equal_field` at row 1' (tx_powermailcond_domain_model_rule:NEW5edd12ff6203e885562589)`

Environment:
TYPO3 10.4.3
PHP 7.3.8
MariaDB: 10.3.16

**Comment by pixeldesu** [comment]
Closing this issue as it's been 4 years and 3 major versions of `powermail_cond`. If the issue still occurs, feel free to reopen this or open a new one.
