### ISSUE TITLE
"invalid integer value" on creating new rule

### ISSUE THREAD

**Issue by TheNaderio** [in2code-de/powermail_cond#48]
Due to the new strict mode, there is this error thrown.

**Comment by TheNaderio** [comment]
should be fixed with PR #49

**Comment by loeffe1** [comment]
equal_field still has an empty string defined as default value

**Comment by mmunz** [comment]
Can confirm and also that PR #49 fixes the issue. A merge would be appreciated.

**Comment by ElectricMud** [comment]
Any chance that an update for this will be available in the near future?

TYPO3 10.4.7
Powermail 8.3.2
Powermail Conditions 8.1.0
