### ISSUE TITLE
TYPO3 V12 compatibility

### ISSUE THREAD

**Issue by mschwemer** [in2code-de/powermail_cond#83]
There will be an EXT:powermail_cond version, which is compatible with TYPO3 core V12. It is currently under development and testing.

If you need early access to this version, please head over to https://www.in2code.de/agentur/typo3-extensions/early-access-programm/ and support our work.

**Comment by mhirdes** [comment]
Hey, are there any plans for an official release? We already use the early access. Just asking.

**Comment by pixeldesu** [comment]
Closed as the v12 compatible version has already been released for a while now.
