### ISSUE TITLE
Umlaut not working

### ISSUE THREAD

**Issue by arminevi** [in2code-de/powermail_cond#90]
I have a Powermail form with a checkbox field with multiple options. There are couple of options which contain umlauts. Take "Tischwäsche" as an example.
![Bildschirmfoto 2024-02-16 um 11 26 28](https://github.com/in2code-de/powermail_cond/assets/93548958/2503fba6-0fdd-4f29-bb3f-14a0382205ec)

The actual field looks like this:
![Bildschirmfoto 2024-02-16 um 11 28 12](https://github.com/in2code-de/powermail_cond/assets/93548958/5eb8d3ba-f319-477c-8785-4a95fdd09379)

For this form I have also defined conditions.
![Bildschirmfoto 2024-02-16 um 11 30 13](https://github.com/in2code-de/powermail_cond/assets/93548958/8c3a38a5-b48d-4662-b76a-4dba55350bb6)

Unfortunately conditions for words with umlauts do not apply. In typo3 v8 it worked but since I updated directly to typo3 v11 these conditions with umlauts don't apply anymore unless I define an optional value "Tischwaesche"

**Comment by runepiper** [comment]
We do have the same issue.

**Comment by runepiper** [comment]
Looks like https://github.com/in2code-de/powermail_cond/pull/85 fixes the issue for EXT:powermail_cond v10. @einpraegsam is it possible to backport the pull request into v10?

**Comment by pixeldesu** [comment]
Support for v10 of Powermail (and its child-extensions) currently only includes Security fixes. However, paid backports to that version are possible. If you would want that, please [enquire with us](https://www.in2code.de/en/contact/).
