### ISSUE TITLE
Flickering of initially hidden fields

### ISSUE THREAD

**Issue by kitzberger** [in2code-de/powermail_cond#93]
Hi,

we've noticed that fields that are initially hidden (by a hide condition) are being displayed for a short time when loading a form in the frontend and are only hidden after the 3132 request has been made and its content processed. This is confusing/irritading to some of our users.

How could this flickering of fields be reduced and the UX be improved?

It should be relatively easy to render the information gathered by ``ConditionController->buildConditionAction()`` to the fieldsets/fields markup directly so the *initial loading* of 3132 could even be skipped and only be performed after the first user input?

I'd like to know whether or not this sounds like a solid approach to you, before digging further into this and start working on a PR.

**Comment by Patta** [comment]
@kitzberger i can confirm this issue. we hide the initial hidden fields with css to avoid this "glitch".

You could insert the css directly into the form with a form field of type html
```
<style>
.powermail_fieldwrap_initialhiddenfieldmarker,
.powermail_fieldwrap_initialhiddenfield2marker
{
display: none;
}
</style>
```

**Comment by kitzberger** [comment]
Yup, something like that, but auto-generated. So our editors wouldn't have to think about that. Maybe a simple viewhelper that outputs that CSS?

**Comment by Patta** [comment]
that would be great indeed! (UX)

**Comment by kitzberger** [comment]
And additionally to the `display:none` we'd have to handle the `required` attribute as well... maybe more?

**Comment by kitzberger** [comment]
@Patta, I've created a PR for the 10.1.x branch of this extension. I appreciate any feedback :-)
